export default [
  {
    type: 'checkbox',
    input: true,
    label: 'Address 1',
    key: 'displayAddress1',
    tooltip: 'When set, this will show the Address 1 field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'Address 2',
    key: 'displayAddress2',
    tooltip: 'When set, this will show the Address 2 field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'Address 3',
    key: 'displayAddress3',
    tooltip: 'When set, this will show the Address 3 field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'City',
    key: 'displayCity',
    tooltip: 'When set, this will show the City field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'Region',
    key: 'displayRegion',
    tooltip: 'When set, this will show the Region field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'Country',
    key: 'displayCountry',
    tooltip: 'When set, this will show the Country field',
    weight: 1,
    defaultValue: true,
  },
  {
    type: 'checkbox',
    input: true,
    label: 'Hide Field Labels',
    key: 'hideFieldLabels',
    tooltip: 'When set, this will hide the field labels',
    weight: 1,
    defaultValue: false,
  }
];
